apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: buckets.platform.org
spec:
  compositeTypeRef:
    apiVersion: platform.org/v1alpha1
    kind: Bucket
  mode: Pipeline
  pipeline:
    - step: compose-kubernetes-object
      functionRef:
        name: public-function-bucket
