apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: strings.internal.platform.org
spec:
  scope: Namespaced
  group: internal.platform.org
  names:
    kind: Strings
    plural: strings
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                value:
                  type: string
                  description: The string value to propagate to the NopResource.
