apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: public-function-bucket
spec:
  package: ${REGISTRY}/public-function-bucket:${FUNCTION_VERSION}
  packagePullPolicy: IfNotPresent
