apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: buckets.internal.platform.org
spec:
  compositeTypeRef:
    apiVersion: internal.platform.org/v1alpha1
    kind: Bucket
  mode: Pipeline
  pipeline:
    - step: compose-s3-resources
      functionRef:
        name: function-bucket
